#!/usr/bin/env python3
"""
generate_data.py
Reads an Excel file with 3 sheets and outputs legacy_data.js

Rules:
- Row 1: special identity (e.g., "JASER", "JASERs")
- Row 2: year (e.g., "25-26", "22-23")
- Row 3+: names.
- There may be 3 empty rows that act as a separator.
- BEFORE the 3 empty rows: each row is a chain (relationship).
- AFTER the 3 empty rows: each row contains isolated individuals (no relationship).
"""

import openpyxl
import json
import sys
import os

def parse_sheet(worksheet):
    # 1) Read headers: row 1 = identity, row 2 = year
    col_info = []
    for col in range(1, worksheet.max_column + 1):
        identity = worksheet.cell(row=1, column=col).value
        year = worksheet.cell(row=2, column=col).value
        if identity is not None and str(identity).strip():
            col_info.append({
                'col': col,
                'identity': str(identity).strip(),
                'year': str(year).strip() if year else ''
            })
        else:
            col_info.append({
                'col': col,
                'identity': '',
                'year': ''
            })

    # Remove columns with no identity
    col_info = [c for c in col_info if c['identity']]
    if not col_info:
        return []

    # 2) Read all data rows from row 3 onward
    rows = []
    for row in range(3, worksheet.max_row + 1):
        row_data = {}
        for info in col_info:
            cell = worksheet.cell(row=row, column=info['col'])
            val = cell.value
            if val is not None and str(val).strip():
                row_data[info['col']] = str(val).strip()
        rows.append(row_data)

    # 3) Find the break: 3 consecutive completely empty rows
    break_row_index = None
    empty_count = 0
    for idx, row in enumerate(rows):
        if not row:
            empty_count += 1
            if empty_count == 3:
                break_row_index = idx - 2
                break
        else:
            empty_count = 0

    if break_row_index is not None:
        before_rows = rows[:break_row_index]
        after_rows = rows[break_row_index + 3:]
    else:
        before_rows = rows
        after_rows = []

    chains = []

    # 4) Process before_rows: each row is a chain (relationship)
    for row_data in before_rows:
        if not row_data:
            continue
        items = []
        for col, name in row_data.items():
            info = next((c for c in col_info if c['col'] == col), None)
            if info:
                items.append({
                    'name': name,
                    'year': info['year'],
                    'label': info['identity'],
                    'col_index': col
                })
        if not items:
            continue
        items.sort(key=lambda x: x['col_index'])
        for item in items:
            del item['col_index']
        total = len(items)
        for i, item in enumerate(items):
            if i == 0:
                item['type'] = 'mentor'      # newest (leftmost)
            elif i == total - 1:
                item['type'] = 'mentee'      # oldest (rightmost)
            else:
                item['type'] = 'bridge'
        chains.append(items)

    # 5) Process after_rows: each name is an isolated node
    for row_data in after_rows:
        if not row_data:
            continue
        for col, name in row_data.items():
            info = next((c for c in col_info if c['col'] == col), None)
            if info:
                chains.append([{
                    'name': name,
                    'year': info['year'],
                    'label': info['identity'],
                    'type': 'isolated'
                }])

    return chains


def main():
    excel_file = r"C:\Users\hugon\Downloads\JASER Tree.xlsx"
    output_js = r"C:\Users\hugon\Downloads\legacy_data.js"

    if not os.path.exists(excel_file):
        print(f"❌ File '{excel_file}' not found. Place your Excel file and rename it to 'your_data.xlsx'")
        sys.exit(1)

    try:
        workbook = openpyxl.load_workbook(excel_file, data_only=True)
    except Exception as e:
        print(f"❌ Failed to load Excel: {e}")
        sys.exit(1)

    sheet_names = workbook.sheetnames
    print(f"📂 Found sheets: {sheet_names}")

    num_sheets = min(3, len(sheet_names))
    data = {}
    for i in range(num_sheets):
        sheet = workbook[sheet_names[i]]
        chains = parse_sheet(sheet)
        key = f'tree{i+1}'
        data[key] = chains
        print(f"✅ Sheet '{sheet_names[i]}': {len(chains)} chains parsed.")

    js_content = "// Auto-generated by generate_data.py\n"
    js_content += "// Do not edit manually.\n\n"
    js_content += "var JASER_DATA = " + json.dumps(data, indent=2) + ";\n"

    with open(output_js, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"✅ Data written to '{output_js}'")
    print("Include this file in your HTML: <script src='legacy_data.js'></script>")


if __name__ == '__main__':
    main()